[package]
name = "patches"
version = "0.1.0"
authors = ["Zack Mullaly <zmullaly@mozilla.com>"]

[features]
integration-test = []  # Only set when integration testing in Docker

[dependencies]
clap = "^2.32"
reqwest = "^0.9"
semver = "^0.9"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
